### ISSUE TITLE
Stylesheet not loading, todos_mobile.css throws error

### ISSUE THREAD

**Issue by zwippie** [sproutcore/Todos-Example#10]
I was having a problem with the file `todos_mobile.css` stylesheet. No style was rendered to the browser at all, sc-server error was:

```
Sass::SyntaxError: Undefined mixin 'border-radius'.
    tmp/chance/home/zwippie/src/todos/tmp/debug/staging/static/todos/en/current/resources/stylesheets/todos_mobile_css.scss:10:in `border-radius'
```

It turns out that the css3 mixins are required but not loaded. Put this on top of `todos_mobile.css` to fix the problem.

```
@import "compass/css3";
```

**Comment by stevens** [comment]
thanks. useful to me

**Comment by Feuda** [comment]
hit my problem, thanks

**Comment by dcporter** [comment]
This is a bug, right? Adding @zwippie's line to the top of the css file fixes it for everyone?
