### ISSUE TITLE
CSS files are actually SCSS

### ISSUE THREAD

**Issue by smathy** [sproutcore/Todos-Example#8]
The CSS files in [the stylesheets directory](https://github.com/sproutcore/Todos-Example/tree/master/apps/todos/resources/stylesheets) are actually SCSS files and break in the 2.0 tutorial.

**Comment by tomdale** [comment]
This repository is for SproutCore 1.6. Please see github.com/sproutcore/todos for the 2.0 version. I'll update the repos to make it more clear when I'm back at a computer.

**Comment by smathy** [comment]
Oh, thanks.

So then the problem here is that [Step 7 in the 2.0 guide](http://guides.sproutcore20.com/getting_started.html#doing-it-with-style) links to todos.css in the wrong repo - because it's linking to **this** repo.

**Comment by chickenkiller** [comment]
Yes, this has already been fixed in the repo: sproutcore/sproutguides#84. Let's wait for it to be deployed.

**Comment by tomdale** [comment]
You guys rule. :D Thank you!
